package fable.hideseek.imba.config;

import com.google.gson.Gson;import com.google.gson.GsonBuilder;import net.fabricmc.loader.api.FabricLoader;import net.minecraft.block.Block;import net.minecraft.block.Blocks;import net.minecraft.entity.EntityType;import net.minecraft.registry.Registries;import net.minecraft.util.Identifier;import java.io.IOException;import java.nio.file.Files;import java.nio.file.Path;import java.nio.file.StandardCopyOption;import java.util.HashSet;import java.util.List;import java.util.Set;
public final class BreakRulesConfig {
 private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create(); private static final Path PATH=FabricLoader.getInstance().getConfigDir().resolve("imba_block_rules.json"),LEGACY_PATH=FabricLoader.getInstance().getConfigDir().resolve("imba_break_rules.json"); private static final Set<Identifier> ADVENTURE_BREAK_BLOCKS=new HashSet<>(),INTERACTIVE_EXCEPTIONS=new HashSet<>(),INTERACTIVE_ENTITY_EXCEPTIONS=new HashSet<>(); private BreakRulesConfig(){}
 public static void load(){ADVENTURE_BREAK_BLOCKS.clear();INTERACTIVE_EXCEPTIONS.clear();INTERACTIVE_ENTITY_EXCEPTIONS.clear();Identifier brewing=Registries.BLOCK.getId(Blocks.BREWING_STAND);ADVENTURE_BREAK_BLOCKS.add(brewing);Path source=Files.exists(PATH)?PATH:LEGACY_PATH;if(Files.exists(source))try{Data data=GSON.fromJson(Files.readString(source),Data.class);if(data!=null){List<String> breakIds=data.adventureBreakBlocks!=null?data.adventureBreakBlocks:data.noPenaltyBreakBlocks;readBlockIds(breakIds,ADVENTURE_BREAK_BLOCKS);readBlockIds(data.interactiveExceptions,INTERACTIVE_EXCEPTIONS);readEntityIds(data.interactiveEntityExceptions,INTERACTIVE_ENTITY_EXCEPTIONS);}}catch(IOException|RuntimeException e){System.err.println("[IMBA] Не удалось загрузить правила блоков/сущностей: "+e.getMessage());}ADVENTURE_BREAK_BLOCKS.add(brewing);save();}
 private static void readBlockIds(List<String> values,Set<Identifier> target){if(values==null)return;for(String raw:values){Identifier id=Identifier.tryParse(raw);if(id!=null&&Registries.BLOCK.containsId(id))target.add(id);}}
 private static void readEntityIds(List<String> values,Set<Identifier> target){if(values==null)return;for(String raw:values){Identifier id=Identifier.tryParse(raw);if(id!=null&&Registries.ENTITY_TYPE.containsId(id))target.add(id);}}
 public static void save(){Data data=new Data(ADVENTURE_BREAK_BLOCKS.stream().map(Identifier::toString).sorted().toList(),INTERACTIVE_EXCEPTIONS.stream().map(Identifier::toString).sorted().toList(),INTERACTIVE_ENTITY_EXCEPTIONS.stream().map(Identifier::toString).sorted().toList(),null);try{Files.createDirectories(PATH.getParent());Path tmp=PATH.resolveSibling(PATH.getFileName()+".tmp");Files.writeString(tmp,GSON.toJson(data));Files.move(tmp,PATH,StandardCopyOption.REPLACE_EXISTING);}catch(IOException e){System.err.println("[IMBA] Не удалось сохранить правила блоков/сущностей: "+e.getMessage());}}
 public static boolean shouldPunishForBreak(Block block){return !isAdventureBreakAllowed(block);} public static boolean isAdventureBreakAllowed(Block block){return block!=null&&ADVENTURE_BREAK_BLOCKS.contains(Registries.BLOCK.getId(block));} public static boolean isInteractiveAllowed(Block block){return block!=null&&INTERACTIVE_EXCEPTIONS.contains(Registries.BLOCK.getId(block));} public static boolean isInteractiveEntityAllowed(EntityType<?> type){return type!=null&&INTERACTIVE_ENTITY_EXCEPTIONS.contains(Registries.ENTITY_TYPE.getId(type));}
 public static void setAdventureBreakAllowed(Identifier id,boolean allowed){if(id==null||!Registries.BLOCK.containsId(id))return;if(allowed)ADVENTURE_BREAK_BLOCKS.add(id);else ADVENTURE_BREAK_BLOCKS.remove(id);ADVENTURE_BREAK_BLOCKS.add(Registries.BLOCK.getId(Blocks.BREWING_STAND));save();}
 public static void setInteractiveAllowed(Identifier id,boolean allowed){if(id==null||!Registries.BLOCK.containsId(id))return;if(allowed)INTERACTIVE_EXCEPTIONS.add(id);else INTERACTIVE_EXCEPTIONS.remove(id);save();}
 public static void setInteractiveEntityAllowed(Identifier id,boolean allowed){if(id==null||!Registries.ENTITY_TYPE.containsId(id))return;if(allowed)INTERACTIVE_ENTITY_EXCEPTIONS.add(id);else INTERACTIVE_ENTITY_EXCEPTIONS.remove(id);save();}
 public static Set<String> adventureBreakSnapshot(){return ADVENTURE_BREAK_BLOCKS.stream().map(Identifier::toString).collect(java.util.stream.Collectors.toUnmodifiableSet());} public static Set<String> interactiveExceptionsSnapshot(){return INTERACTIVE_EXCEPTIONS.stream().map(Identifier::toString).collect(java.util.stream.Collectors.toUnmodifiableSet());} public static Set<String> interactiveEntityExceptionsSnapshot(){return INTERACTIVE_ENTITY_EXCEPTIONS.stream().map(Identifier::toString).collect(java.util.stream.Collectors.toUnmodifiableSet());}
 private static final class Data{List<String> adventureBreakBlocks;List<String> interactiveExceptions;List<String> interactiveEntityExceptions;List<String> noPenaltyBreakBlocks;Data(List<String>a,List<String>i,List<String>e,List<String>n){adventureBreakBlocks=a;interactiveExceptions=i;interactiveEntityExceptions=e;noPenaltyBreakBlocks=n;}}
}
