package fable.hideseek.imba.config;

import com.google.gson.Gson;import com.google.gson.GsonBuilder;import net.fabricmc.loader.api.FabricLoader;import java.io.IOException;import java.nio.file.Files;import java.nio.file.Path;import java.nio.file.StandardCopyOption;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;
public final class MessageSettingsConfig {
 public record Entry(String key,String title,boolean defaultEnabled){}
 public static final List<Entry> CATALOG=List.of(new Entry("restriction.item_frame","Рамки: предметы можно класть только в Creative",false),new Entry("restriction.interactive_block","Запрещён интерактивный блок",false),new Entry("restriction.interactive_entity","Запрещена интерактивная сущность",false),new Entry("restriction.chest_during_game","Во время игры нельзя открывать сундуки",false),new Entry("restriction.team_change","Во время игры нельзя менять команду",false),new Entry("mask.need_model","Сначала надень модель",false),new Entry("mask.air_forbidden","Нельзя зафиксироваться в воздухе",false),new Entry("mask.air_requires_block","Для фиксации требуется определённый блок",false),new Entry("mask.no_space","В конечной точке маскировки недостаточно места",false),new Entry("mask.model_equipped","Надета модель",false),new Entry("mask.statue_enter","Вы зафиксировались",false),new Entry("mask.statue_exit","Вы вышли из режима фиксации",false),new Entry("wall_climb.state","Ползание по стенам: ВКЛ/ВЫКЛ",false),new Entry("wall_climb.unsupported","Эта маскировка не умеет ползать",false),new Entry("hint.mask_controls","Подсказка клавиш вращения/ползания",true),new Entry("seeker.eliminated","У искателя закончились сердца",true),new Entry("game.already_running","Игра уже запущена",false),new Entry("game.start_requirements","Для запуска нужны минимум 2 игрока",true),new Entry("game.pause","Игра поставлена на паузу",true),new Entry("game.resume","Игра продолжена",true),new Entry("game.auto_pause","Автопауза при выходе ключевого игрока",true),new Entry("game.auto_resume","Автопродолжение после возвращения игроков",true),new Entry("game.prepare","Раунд начался / время спрятаться",true),new Entry("game.seekers_released","Искатели выпущены",true),new Entry("game.round_result","Сообщение о победе/поражении",true),new Entry("game.round_reset","Раунд полностью сброшен",true),new Entry("game.test_timer","Сообщения тестового таймера",false));
 private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create();private static final Path PATH=FabricLoader.getInstance().getConfigDir().resolve("imba_messages.json");private static final Map<String,Boolean> ENABLED=new LinkedHashMap<>();private MessageSettingsConfig(){}
 public static void load(){resetDefaults();if(!Files.exists(PATH)){save();return;}try{Data data=GSON.fromJson(Files.readString(PATH),Data.class);if(data!=null&&data.enabled!=null)for(Entry entry:CATALOG)if(data.enabled.containsKey(entry.key()))ENABLED.put(entry.key(),Boolean.TRUE.equals(data.enabled.get(entry.key())));}catch(IOException|RuntimeException e){System.err.println("[IMBA] Не удалось загрузить настройки сообщений: "+e.getMessage());}}
 public static boolean isEnabled(String key){Entry entry=entry(key);if(entry==null)return true;return ENABLED.getOrDefault(key,entry.defaultEnabled());}public static void setEnabled(String key,boolean enabled){if(entry(key)==null)return;ENABLED.put(key,enabled);save();}public static Map<String,Boolean> snapshot(){return Map.copyOf(ENABLED);}
 public static String keyForText(String text){if(text==null||text.isBlank())return null;String clean=text.replaceAll("§.","").toLowerCase(java.util.Locale.ROOT);if(clean.contains("рамк")&&clean.contains("креатив"))return "restriction.item_frame";if(clean.contains("интерактив")&&clean.contains("блок"))return "restriction.interactive_block";if(clean.contains("интерактив")&&(clean.contains("сущност")||clean.contains("вагонет")))return "restriction.interactive_entity";if(clean.contains("нельзя открывать сундук")||clean.contains("нельзя открывать сундуки"))return "restriction.chest_during_game";if(clean.contains("менять команду нельзя"))return "restriction.team_change";if(clean.contains("сначала надень")&&(clean.contains("маскиров")||clean.contains("модел")))return "mask.need_model";if(clean.contains("нельзя зафиксироваться в воздухе"))return "mask.air_forbidden";if(clean.contains("для фиксации")&&clean.contains("блок"))return "mask.air_requires_block";if(clean.contains("недостаточно места")&&clean.contains("маскиров"))return "mask.no_space";if(clean.contains("надета модель"))return "mask.model_equipped";if(clean.contains("зафиксировал"))return "mask.statue_enter";if(clean.contains("вышли из режима")&&clean.contains("фикс"))return "mask.statue_exit";if(clean.contains("ползание")&&(clean.contains("вкл")||clean.contains("выкл")))return "wall_climb.state";if(clean.contains("не умеет ползать"))return "wall_climb.unsupported";if(clean.contains("игра уже запущена"))return "game.already_running";return null;}public static boolean shouldShowText(String text){String key=keyForText(text);return key==null||isEnabled(key);}
 public static void save(){try{Files.createDirectories(PATH.getParent());Path tmp=PATH.resolveSibling(PATH.getFileName()+".tmp");Files.writeString(tmp,GSON.toJson(new Data(new LinkedHashMap<>(ENABLED))));Files.move(tmp,PATH,StandardCopyOption.REPLACE_EXISTING);}catch(IOException e){System.err.println("[IMBA] Не удалось сохранить настройки сообщений: "+e.getMessage());}}
 private static Entry entry(String key){if(key==null)return null;for(Entry entry:CATALOG)if(entry.key().equals(key))return entry;return null;}private static void resetDefaults(){ENABLED.clear();for(Entry entry:CATALOG)ENABLED.put(entry.key(),entry.defaultEnabled());}private record Data(Map<String,Boolean> enabled){}
}
