package fable.hideseek.imba.client;

import fable.hideseek.imba.net.BlockRulesNetworking;import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;import net.minecraft.block.Block;import net.minecraft.client.gui.DrawContext;import net.minecraft.client.gui.screen.Screen;import net.minecraft.client.gui.widget.ButtonWidget;import net.minecraft.client.gui.widget.TextFieldWidget;import net.minecraft.entity.EntityType;import net.minecraft.item.ItemStack;import net.minecraft.network.PacketByteBuf;import net.minecraft.registry.Registries;import net.minecraft.text.Text;import net.minecraft.util.Identifier;import net.minecraft.util.math.MathHelper;import java.util.ArrayList;import java.util.Comparator;import java.util.HashSet;import java.util.List;import java.util.Locale;import java.util.Set;
public final class BlockRulesScreen extends Screen{
 private static final int ROW_HEIGHT=24;private final List<Entry>blockEntries=new ArrayList<>(),entityEntries=new ArrayList<>(),filtered=new ArrayList<>();private final Set<String>interactive=new HashSet<>(),breakable=new HashSet<>(),interactiveEntities=new HashSet<>();private TextFieldWidget search;private ButtonWidget tabButton;private int tab,scroll;private boolean synced;
 public BlockRulesScreen(){super(Text.literal("Исключения карты"));for(Block block:Registries.BLOCK){Identifier id=Registries.BLOCK.getId(block);if(id!=null)blockEntries.add(new Entry(id,block.getName().getString(),block));}for(EntityType<?> type:Registries.ENTITY_TYPE){Identifier id=Registries.ENTITY_TYPE.getId(type);if(id!=null)entityEntries.add(new Entry(id,type.getName().getString(),null));}Comparator<Entry>cmp=Comparator.comparing(e->e.id.toString());blockEntries.sort(cmp);entityEntries.sort(cmp);rebuild();}
 @Override protected void init(){int w=Math.min(620,width-24),left=(width-w)/2;tabButton=addDrawableChild(ButtonWidget.builder(tabText(),b->{tab=(tab+1)%3;b.setMessage(tabText());scroll=0;rebuild();}).dimensions(left+12,34,w-24,20).build());search=new TextFieldWidget(textRenderer,left+12,58,w-24,20,Text.empty());search.setPlaceholder(Text.literal("Поиск по названию или ID..."));search.setChangedListener(v->{rebuild();scroll=0;});addDrawableChild(search);addDrawableChild(ButtonWidget.builder(Text.literal("Закрыть"),b->close()).dimensions(width/2-55,height-30,110,20).build());ClientPlayNetworking.send(BlockRulesNetworking.REQUEST,PacketByteBufs.empty());}
 private Text tabText(){return Text.literal(switch(tab){case 0->"Вкладка: исключения интерактивных блоков";case 1->"Вкладка: можно ломать в Adventure";default->"Вкладка: интерактивные сущности";});}
 public void applyServerState(Set<String>a,Set<String>b,Set<String>e){interactive.clear();interactive.addAll(a);breakable.clear();breakable.addAll(b);interactiveEntities.clear();interactiveEntities.addAll(e);synced=true;}
 private void rebuild(){String n=search==null?"":search.getText().trim().toLowerCase(Locale.ROOT);filtered.clear();for(Entry e:tab==2?entityEntries:blockEntries)if(n.isEmpty()||e.id.toString().toLowerCase(Locale.ROOT).contains(n)||e.name.toLowerCase(Locale.ROOT).contains(n))filtered.add(e);clamp();}
 private Set<String> active(){return tab==0?interactive:tab==1?breakable:interactiveEntities;}private int top(){return 86;}private int bottom(){return height-42;}private int rows(){return Math.max(1,(bottom()-top())/ROW_HEIGHT);}private void clamp(){scroll=MathHelper.clamp(scroll,0,Math.max(0,filtered.size()-rows()));}
 @Override public void render(DrawContext c,int mx,int my,float d){renderBackground(c);int w=Math.min(620,width-24),left=(width-w)/2,right=left+w;c.fill(left,8,right,height-36,0xDD181818);c.drawCenteredTextWithShadow(textRenderer,title,width/2,16,0xFFFFFF);String hint=!synced?"Получение настроек с сервера...":switch(tab){case 0->"Зелёные блоки разрешено открывать/использовать не в Creative";case 1->"Зелёные блоки можно ломать в Adventure, но без дропа и XP";default->"Зелёные интерактивные сущности разрешено использовать";};c.drawCenteredTextWithShadow(textRenderer,hint,width/2,79,synced?0xAAAAAA:0xFFFF55);clamp();int rl=left+12,rr=right-12,y=top();Set<String>a=active();for(int row=0;row<rows();row++){int i=scroll+row;if(i>=filtered.size())break;Entry e=filtered.get(i);boolean enabled=a.contains(e.id.toString());c.fill(rl,y,rr,y+21,(i&1)==0?0x55303030:0x55404040);int tx=rl+4;if(e.block!=null){ItemStack icon=new ItemStack(e.block.asItem());if(!icon.isEmpty()){c.drawItem(icon,rl+2,y+2);tx=rl+22;}}c.drawTextWithShadow(textRenderer,e.name,tx,y+2,0xFFFFFF);c.drawTextWithShadow(textRenderer,e.id.toString(),tx,y+11,0x888888);int sl=rr-105;c.fill(sl,y+2,rr-2,y+19,enabled?0xAA1E6B2D:0xAA5A2020);c.drawCenteredTextWithShadow(textRenderer,enabled?"РАЗРЕШЕНО":"ЗАПРЕЩЕНО",sl+51,y+7,enabled?0xAAFFAA:0xFFFFAA);y+=ROW_HEIGHT;}super.render(c,mx,my,d);}
 @Override public boolean mouseClicked(double mx,double my,int button){if(super.mouseClicked(mx,my,button))return true;if(button!=0||!synced)return false;int w=Math.min(620,width-24),left=(width-w)/2,rl=left+12,rr=left+w-12;if(mx<rl||mx>=rr||my<top()||my>=bottom())return false;int i=scroll+(int)((my-top())/ROW_HEIGHT);if(i<0||i>=filtered.size())return false;Entry e=filtered.get(i);Set<String>a=active();boolean value=!a.contains(e.id.toString());if(value)a.add(e.id.toString());else a.remove(e.id.toString());PacketByteBuf buf=PacketByteBufs.create();buf.writeByte(tab);buf.writeString(e.id.toString(),256);buf.writeBoolean(value);ClientPlayNetworking.send(BlockRulesNetworking.SET,buf);return true;}
 @Override public boolean mouseScrolled(double mx,double my,double amount){if(amount!=0){scroll-=(int)Math.signum(amount)*3;clamp();return true;}return super.mouseScrolled(mx,my,amount);}@Override public boolean shouldPause(){return false;}private record Entry(Identifier id,String name,Block block){}
}
