package fable.hideseek.imba.client;

import fable.hideseek.imba.config.MaskHitboxConfig;
import fable.hideseek.imba.net.MaskHitboxNetworking;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;
import net.fabricmc.fabric.api.networking.v1.PacketByteBufs;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.widget.ButtonWidget;
import net.minecraft.client.gui.widget.TextFieldWidget;
import net.minecraft.network.PacketByteBuf;
import net.minecraft.registry.Registries;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.MathHelper;
import java.util.ArrayList;import java.util.Comparator;import java.util.List;import java.util.Locale;
public final class MaskHitboxConfigScreen extends Screen {
    private static final int ROW_HEIGHT=24;private final List<String> filtered=new ArrayList<>();private TextFieldWidget search,minX,minY,minZ,maxX,maxY,maxZ;private int scroll;public MaskHitboxConfigScreen(){super(Text.literal("Хитбоксы маскировок"));}
    @Override protected void init(){int left=width/2-300,top=Math.max(15,height/2-145);search=new TextFieldWidget(textRenderer,left,top+28,280,20,Text.empty());search.setPlaceholder(Text.literal("Поиск блока..."));search.setChangedListener(v->{scroll=0;rebuild();});addDrawableChild(search);minX=field(left+315,top+72,78);minY=field(left+399,top+72,78);minZ=field(left+483,top+72,78);maxX=field(left+315,top+116,78);maxY=field(left+399,top+116,78);maxZ=field(left+483,top+116,78);addDrawableChild(ButtonWidget.builder(Text.literal("Сохранить хитбокс"),b->save()).dimensions(left+315,top+158,246,20).build());addDrawableChild(ButtonWidget.builder(Text.literal("Вернуть стандартный hitbox"),b->reset()).dimensions(left+315,top+184,246,20).build());addDrawableChild(ButtonWidget.builder(Text.literal("Закрыть"),b->close()).dimensions(left+315,top+230,246,20).build());rebuild();ClientPlayNetworking.send(MaskHitboxNetworking.REQUEST,PacketByteBufs.empty());}
    private TextFieldWidget field(int x,int y,int w){var f=new TextFieldWidget(textRenderer,x,y,w,20,Text.empty());f.setMaxLength(8);addDrawableChild(f);return f;}public void applyServerState(){rebuild();if(MaskHitboxClientData.selectedId.isEmpty()&&!filtered.isEmpty())select(filtered.get(0));else refreshFields();}
    private void rebuild(){String q=search==null?"":search.getText().trim().toLowerCase(Locale.ROOT);filtered.clear();for(String id:MaskHitboxClientData.snapshot().keySet()){Identifier parsed=Identifier.tryParse(id);String name=parsed!=null&&Registries.BLOCK.containsId(parsed)?Registries.BLOCK.get(parsed).getName().getString():id;if(q.isEmpty()||id.toLowerCase(Locale.ROOT).contains(q)||name.toLowerCase(Locale.ROOT).contains(q))filtered.add(id);}filtered.sort(Comparator.naturalOrder());clamp();}
    private void select(String id){MaskHitboxClientData.selectedId=id;refreshFields();}private void refreshFields(){var e=MaskHitboxClientData.get(MaskHitboxClientData.selectedId);if(e==null||minX==null)return;var b=e.bounds();minX.setText(fmt(b.minX));minY.setText(fmt(b.minY));minZ.setText(fmt(b.minZ));maxX.setText(fmt(b.maxX));maxY.setText(fmt(b.maxY));maxZ.setText(fmt(b.maxZ));}private String fmt(float v){return String.format(Locale.ROOT,"%.2f",v);}private float parse(TextFieldWidget f){return Float.parseFloat(f.getText().replace(',','.'));}
    private void save(){if(MaskHitboxClientData.selectedId.isEmpty())return;try{PacketByteBuf b=PacketByteBufs.create();b.writeString(MaskHitboxClientData.selectedId,256);b.writeFloat(parse(minX));b.writeFloat(parse(minY));b.writeFloat(parse(minZ));b.writeFloat(parse(maxX));b.writeFloat(parse(maxY));b.writeFloat(parse(maxZ));ClientPlayNetworking.send(MaskHitboxNetworking.SET,b);}catch(NumberFormatException ignored){}}private void reset(){if(MaskHitboxClientData.selectedId.isEmpty())return;PacketByteBuf b=PacketByteBufs.create();b.writeString(MaskHitboxClientData.selectedId,256);ClientPlayNetworking.send(MaskHitboxNetworking.RESET,b);}private int listTop(){return Math.max(15,height/2-145)+58;}private int listBottom(){return height-42;}private int rows(){return Math.max(1,(listBottom()-listTop())/ROW_HEIGHT);}private void clamp(){scroll=MathHelper.clamp(scroll,0,Math.max(0,filtered.size()-rows()));}
    @Override public void render(DrawContext c,int mx,int my,float d){renderBackground(c);int left=width/2-300,top=Math.max(15,height/2-145);c.fill(left-8,8,left+570,height-36,0xDD181818);c.drawCenteredTextWithShadow(textRenderer,title,width/2,16,0xFFFFFFFF);c.drawTextWithShadow(textRenderer,"Все зарегистрированные блоки Minecraft и модов",left,top+14,0xFFAAAAAA);clamp();int y=listTop();for(int row=0;row<rows();row++){int i=scroll+row;if(i>=filtered.size())break;String id=filtered.get(i);Identifier parsed=Identifier.tryParse(id);String name=parsed!=null&&Registries.BLOCK.containsId(parsed)?Registries.BLOCK.get(parsed).getName().getString():id;boolean selected=id.equals(MaskHitboxClientData.selectedId);c.fill(left,y,left+280,y+21,selected?0xAA3A5A78:0x55303030);c.drawTextWithShadow(textRenderer,name,left+4,y+2,0xFFFFFFFF);c.drawTextWithShadow(textRenderer,id,left+4,y+11,0xFF888888);y+=ROW_HEIGHT;}c.drawTextWithShadow(textRenderer,"MIN X",left+315,top+58,0xFFCCCCCC);c.drawTextWithShadow(textRenderer,"MIN Y",left+399,top+58,0xFFCCCCCC);c.drawTextWithShadow(textRenderer,"MIN Z",left+483,top+58,0xFFCCCCCC);c.drawTextWithShadow(textRenderer,"MAX X",left+315,top+102,0xFFCCCCCC);c.drawTextWithShadow(textRenderer,"MAX Y",left+399,top+102,0xFFCCCCCC);c.drawTextWithShadow(textRenderer,"MAX Z",left+483,top+102,0xFFCCCCCC);c.drawTextWithShadow(textRenderer,"Координаты в пикселях 0..16. Рамка отображается в мире на маскировке.",left+315,top+212,0xFF888888);super.render(c,mx,my,d);}
    @Override public boolean mouseClicked(double mx,double my,int button){if(super.mouseClicked(mx,my,button))return true;if(button!=0)return false;int left=width/2-300;if(mx<left||mx>=left+280||my<listTop()||my>=listBottom())return false;int i=scroll+(int)((my-listTop())/ROW_HEIGHT);if(i>=0&&i<filtered.size()){select(filtered.get(i));return true;}return false;}@Override public boolean mouseScrolled(double mx,double my,double amount){if(amount!=0){scroll-=(int)Math.signum(amount)*3;clamp();return true;}return super.mouseScrolled(mx,my,amount);}@Override public boolean shouldPause(){return false;}
}
