package fable.hideseek.imba.net;

import fable.hideseek.imba.config.TeleportConfig;import fable.hideseek.imba.game.GameConfig;import fable.hideseek.imba.game.RoundDefinition;import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;import net.minecraft.registry.RegistryKey;import net.minecraft.server.world.ServerWorld;import net.minecraft.text.Text;import net.minecraft.util.Identifier;import net.minecraft.util.math.Vec3d;import net.minecraft.world.World;
public final class TeleportToolNetworking {
 public static final Identifier SAVE=new Identifier("imba","teleport_tool_save"),TEST=new Identifier("imba","teleport_tool_test");private TeleportToolNetworking(){}
 public static void register(){
  ServerPlayNetworking.registerGlobalReceiver(SAVE,(server,player,handler,buf,sender)->{String slot=buf.readString(32);double x=buf.readDouble(),y=buf.readDouble(),z=buf.readDouble();float yaw=buf.readFloat(),pitch=buf.readFloat();server.execute(()->{if(!player.hasPermissionLevel(2)||!isTeleportSlot(slot)||!finite(x,y,z,yaw,pitch)){player.sendMessage(Text.literal("§cНе удалось сохранить точку телепортации"),true);return;}setPoint(slot,new Vec3d(x,y,z),yaw,pitch);TeleportConfig.save();player.sendMessage(Text.literal("§aАвтосохранено: §f"+displayName(slot)+" §7→ §f"+fmt(x)+", "+fmt(y)+", "+fmt(z)),true);});});
  ServerPlayNetworking.registerGlobalReceiver(TEST,(server,player,handler,buf,sender)->{String slot=buf.readString(32);server.execute(()->{if(!player.hasPermissionLevel(2))return;TeleportPoint p=getPoint(slot);if(p==null){player.sendMessage(Text.literal("§cТочка телепортации не настроена"),true);return;}ServerWorld w=server.getWorld(p.worldKey);if(w!=null)player.teleport(w,p.pos.x,p.pos.y,p.pos.z,p.yaw,p.pitch);});});
 }
 private static boolean isTeleportSlot(String s){if(s==null)return false;if("lobby".equalsIgnoreCase(s))return true;if(parsePrepare(s)>=0)return true;ParsedSlot p=parseRound(s);return p!=null&&p.index>=0&&p.index<GameConfig.ROUNDS.size();}
 private static void setPoint(String s,Vec3d pos,float yaw,float pitch){if("lobby".equalsIgnoreCase(s)){GameConfig.LOBBY_POS=pos;GameConfig.LOBBY_YAW=yaw;GameConfig.LOBBY_PITCH=pitch;return;}int extra=parsePrepare(s);if(extra>=0){TeleportConfig.setExtraSeekerPrepare(extra,pos,yaw,pitch);return;}ParsedSlot p=parseRound(s);if(p==null)return;RoundDefinition r=GameConfig.ROUNDS.get(p.index);if(p.hider){r.hiderPos=pos;r.hiderYaw=yaw;r.hiderPitch=pitch;}else{r.seekerPos=pos;r.seekerYaw=yaw;r.seekerPitch=pitch;}}
 private static TeleportPoint getPoint(String s){if("lobby".equalsIgnoreCase(s))return new TeleportPoint(World.OVERWORLD,GameConfig.LOBBY_POS,GameConfig.LOBBY_YAW,GameConfig.LOBBY_PITCH);int extra=parsePrepare(s);if(extra>=0){var p=TeleportConfig.getExtraSeekerPrepare(extra);return p==null?null:new TeleportPoint(World.OVERWORLD,p.pos(),p.yaw(),p.pitch());}ParsedSlot p=parseRound(s);if(p==null||p.index<0||p.index>=GameConfig.ROUNDS.size())return null;RoundDefinition r=GameConfig.ROUNDS.get(p.index);return p.hider?new TeleportPoint(r.worldKey,r.hiderPos,r.hiderYaw,r.hiderPitch):new TeleportPoint(r.worldKey,r.seekerPos,r.seekerYaw,r.seekerPitch);}
 private static String displayName(String s){int extra=parsePrepare(s);return extra>=0?"промежуточный спавн доп. искателя №"+(extra+2):GameConfig.getPointDisplayName(s);}
 private static int parsePrepare(String s){if(s==null||!s.toLowerCase(java.util.Locale.ROOT).startsWith("prepare_seeker_"))return-1;try{int n=Integer.parseInt(s.substring("prepare_seeker_".length()));return n>=2&&n<=32?n-2:-1;}catch(Exception e){return-1;}}
 private static ParsedSlot parseRound(String s){if(s==null)return null;String v=s.toLowerCase(java.util.Locale.ROOT);int u=v.indexOf('_');if(!v.startsWith("r")||u<=1)return null;boolean h;if(v.substring(u+1).equals("hider"))h=true;else if(v.substring(u+1).equals("seeker"))h=false;else return null;try{return new ParsedSlot(Integer.parseInt(v.substring(1,u))-1,h);}catch(Exception e){return null;}}
 private static boolean finite(double x,double y,double z,float yaw,float pitch){return Double.isFinite(x)&&Double.isFinite(y)&&Double.isFinite(z)&&Float.isFinite(yaw)&&Float.isFinite(pitch)&&Math.abs(x)<=3e7&&Math.abs(y)<=2048&&Math.abs(z)<=3e7&&Math.abs(pitch)<=90;}
 private static String fmt(double d){return String.format(java.util.Locale.ROOT,"%.2f",d);}private record ParsedSlot(int index,boolean hider){}private record TeleportPoint(RegistryKey<World> worldKey,Vec3d pos,float yaw,float pitch){}
}
